// Regras puras (sem Firebase) do link de WhatsApp dos serviços. Usado por servicesService.ts e testado em Node.

export const WHATSAPP_NOT_CONFIGURED_MESSAGE =
  'O número de WhatsApp padrão não está configurado ou é inválido. Configure-o em Configurações antes de salvar o serviço.';
export const INVALID_MANUAL_LINK_MESSAGE =
  'O link do WhatsApp informado é inválido. Utilize um formato válido (ex: https://wa.me/5531999044206).';

const VALID_HOSTS = ['wa.me', 'api.whatsapp.com', 'web.whatsapp.com', 'chat.whatsapp.com'];

/** Aceita http(s) em wa.me, api/web/chat.whatsapp.com. Rejeita vazio e esquemas inseguros. */
export function isValidWhatsAppUrl(url) {
  if (!url || typeof url !== 'string') return false;
  try {
    const parsed = new URL(url.trim());
    if (parsed.protocol !== 'https:' && parsed.protocol !== 'http:') return false;
    return VALID_HOSTS.some((h) => parsed.hostname === h || parsed.hostname.endsWith(`.${h}`));
  } catch {
    return false;
  }
}

export const buildServiceMessage = (title) =>
  `Olá, gostaria de saber mais sobre os serviços do Herói da Cidade! Tenho interesse no ${title}`;

/** Link com mensagem pré-preenchida a partir do número padrão. Lança erro claro se o número for ausente/inválido. */
export function buildServiceWhatsAppUrl(baseUrl, title) {
  const base = String(baseUrl ?? '').trim();
  if (!isValidWhatsAppUrl(base)) throw new Error(WHATSAPP_NOT_CONFIGURED_MESSAGE);
  const u = new URL(base);
  const hasPhone = u.hostname === 'wa.me'
    ? /^\/\d{8,}$/.test(u.pathname)
    : /^\d{8,}$/.test(u.searchParams.get('phone') ?? '');
  if (!hasPhone) throw new Error(WHATSAPP_NOT_CONFIGURED_MESSAGE);
  u.searchParams.delete('text');
  // encodeURIComponent gera %20 (não "+") e codifica acentos, & e %
  return `${u.toString()}${u.search ? '&' : '?'}text=${encodeURIComponent(buildServiceMessage(title))}`;
}

/** Documentos antigos (sem whatsappUrlSource): o link parece ter sido gerado a partir deste título? */
export function looksAutoGenerated(url, title) {
  if (!isValidWhatsAppUrl(url) || !title) return false;
  try {
    return (new URL(url).searchParams.get('text') ?? '').endsWith(title);
  } catch {
    return false;
  }
}

/** Criação: link manual (validado) ou gerado. Retorna os campos a gravar. */
export function planCreateWhatsApp({ manualUrl, title, baseUrl }) {
  const manual = manualUrl?.trim();
  if (manual) {
    if (!isValidWhatsAppUrl(manual)) throw new Error(INVALID_MANUAL_LINK_MESSAGE);
    return { whatsappUrl: manual, whatsappUrlSource: 'manual' };
  }
  return { whatsappUrl: buildServiceWhatsAppUrl(baseUrl, title), whatsappUrlSource: 'auto' };
}

/**
 * Edição: retorna só o que muda ({} = preservar). `getBaseUrl` só é chamado se for preciso gerar.
 * Documento antigo sem source só é regenerado se o link atual parece gerado do título anterior.
 */
export async function planUpdateWhatsApp({ manualUrl, title, current, getBaseUrl }) {
  const manual = manualUrl?.trim();
  if (manual) {
    if (!isValidWhatsAppUrl(manual)) throw new Error(INVALID_MANUAL_LINK_MESSAGE);
    return { whatsappUrl: manual, whatsappUrlSource: 'manual' };
  }
  if (title === undefined || !current || current.internalOnly || current.title === title) return {};
  const source = current.whatsappUrlSource;
  const regenerate = source === 'auto'
    || (source === undefined && (!current.whatsappUrl || looksAutoGenerated(current.whatsappUrl, current.title)));
  if (!regenerate) return {};
  return { whatsappUrl: buildServiceWhatsAppUrl(await getBaseUrl(), title), whatsappUrlSource: 'auto' };
}

/** Mudança do número padrão: só serviços marcados 'auto' (nunca manuais, antigos ou internos). */
export function planAutoLinkSync(docs, baseUrl) {
  const changes = [];
  for (const { id, data } of docs) {
    if (data.whatsappUrlSource !== 'auto' || data.internalOnly) continue;
    const whatsappUrl = buildServiceWhatsAppUrl(baseUrl, data.title);
    if (whatsappUrl !== data.whatsappUrl) changes.push({ id, whatsappUrl });
  }
  return changes;
}
