import test from 'node:test';
import assert from 'node:assert/strict';
import {
  buildServiceWhatsAppUrl, planCreateWhatsApp, planUpdateWhatsApp, planAutoLinkSync,
  looksAutoGenerated, isValidWhatsAppUrl, WHATSAPP_NOT_CONFIGURED_MESSAGE, INVALID_MANUAL_LINK_MESSAGE,
} from './serviceWhatsApp.js';

const BASE = 'https://wa.me/5531999044206';
const PREFIX = 'Olá, gostaria de saber mais sobre os serviços do Herói da Cidade! Tenho interesse no ';
const textOf = (url) => new URL(url).searchParams.get('text');

test('gera link com o número configurado e a mensagem do título', () => {
  const url = buildServiceWhatsAppUrl(BASE, 'Vídeo Convite');
  assert.ok(url.startsWith(`${BASE}?text=`));
  assert.equal(textOf(url), `${PREFIX}Vídeo Convite`);
});

test('acentos, espaços e especiais são codificados (%20, nunca "+" nem caracteres crus)', () => {
  const url = buildServiceWhatsAppUrl(BASE, 'Vídeo & Cia 100% #1?');
  const query = url.split('?text=')[1];
  assert.match(query, /^[A-Za-z0-9%._~!*'()-]+$/);
  assert.ok(!query.includes('+') && !query.includes(' '));
  assert.equal(textOf(url), `${PREFIX}Vídeo & Cia 100% #1?`);
});

test('formato api.whatsapp.com preserva phone e substitui text existente', () => {
  const url = buildServiceWhatsAppUrl('https://api.whatsapp.com/send?phone=5531999044206&text=velho', 'X');
  const u = new URL(url);
  assert.equal(u.searchParams.get('phone'), '5531999044206');
  assert.equal(u.searchParams.getAll('text').length, 1);
  assert.equal(u.searchParams.get('text'), `${PREFIX}X`);
});

test('número ausente ou inválido não gera link', () => {
  for (const bad of [undefined, null, '', '   ', 'abc', 'javascript:alert(1)', 'https://example.com/5531999044206', 'https://wa.me/', 'https://wa.me/abc', 'https://api.whatsapp.com/send']) {
    assert.throws(() => buildServiceWhatsAppUrl(bad, 'T'), { message: WHATSAPP_NOT_CONFIGURED_MESSAGE }, String(bad));
  }
});

test('criação sem link manual: gera e marca como auto', () => {
  const r = planCreateWhatsApp({ title: 'T', baseUrl: BASE });
  assert.equal(r.whatsappUrlSource, 'auto');
  assert.equal(r.whatsappUrl, buildServiceWhatsAppUrl(BASE, 'T'));
});

test('criação sem link e sem número configurado falha com mensagem clara', () => {
  assert.throws(() => planCreateWhatsApp({ title: 'T', baseUrl: undefined }), { message: WHATSAPP_NOT_CONFIGURED_MESSAGE });
});

test('criação com link manual válido: preserva e marca manual (não exige número padrão)', () => {
  const manual = 'https://wa.me/5511988887777?text=oi';
  assert.deepEqual(planCreateWhatsApp({ manualUrl: ` ${manual} `, title: 'T', baseUrl: undefined }), { whatsappUrl: manual, whatsappUrlSource: 'manual' });
});

test('criação com link manual inválido é rejeitada (sem cair no automático)', () => {
  for (const bad of ['https://evil.com/x', 'javascript:alert(1)', 'nao-e-url']) {
    assert.throws(() => planCreateWhatsApp({ manualUrl: bad, title: 'T', baseUrl: BASE }), { message: INVALID_MANUAL_LINK_MESSAGE });
  }
});

const getBaseUrl = async () => BASE;
const never = async () => { throw new Error('não deveria buscar o número'); };

test('edição com título alterado regenera link auto', async () => {
  const current = { title: 'Antigo', whatsappUrl: buildServiceWhatsAppUrl(BASE, 'Antigo'), whatsappUrlSource: 'auto' };
  const r = await planUpdateWhatsApp({ title: 'Novo', current, getBaseUrl });
  assert.equal(r.whatsappUrlSource, 'auto');
  assert.equal(textOf(r.whatsappUrl), `${PREFIX}Novo`);
});

test('edição sem alteração de título preserva o link e não consulta o número', async () => {
  const current = { title: 'Igual', whatsappUrl: 'https://wa.me/1?x', whatsappUrlSource: 'auto' };
  assert.deepEqual(await planUpdateWhatsApp({ title: 'Igual', current, getBaseUrl: never }), {});
  assert.deepEqual(await planUpdateWhatsApp({ title: undefined, current, getBaseUrl: never }), {});
});

test('edição preserva link manual mesmo com título alterado', async () => {
  const current = { title: 'A', whatsappUrl: 'https://wa.me/5511988887777', whatsappUrlSource: 'manual' };
  assert.deepEqual(await planUpdateWhatsApp({ title: 'B', current, getBaseUrl: never }), {});
});

test('edição com novo link manual válido grava manual; inválido é rejeitado', async () => {
  const current = { title: 'A', whatsappUrl: 'x', whatsappUrlSource: 'auto' };
  assert.deepEqual(await planUpdateWhatsApp({ manualUrl: 'https://wa.me/5511988887777', title: 'B', current, getBaseUrl: never }),
    { whatsappUrl: 'https://wa.me/5511988887777', whatsappUrlSource: 'manual' });
  await assert.rejects(planUpdateWhatsApp({ manualUrl: 'https://evil.com', current, getBaseUrl: never }), { message: INVALID_MANUAL_LINK_MESSAGE });
});

test('edição de título com número ausente falha em vez de gravar link ruim', async () => {
  const current = { title: 'A', whatsappUrl: 'x', whatsappUrlSource: 'auto' };
  await assert.rejects(planUpdateWhatsApp({ title: 'B', current, getBaseUrl: async () => undefined }), { message: WHATSAPP_NOT_CONFIGURED_MESSAGE });
});

test('serviço interno nunca é alterado', async () => {
  const current = { title: 'Interno', whatsappUrl: '', internalOnly: true, whatsappUrlSource: 'auto' };
  assert.deepEqual(await planUpdateWhatsApp({ title: 'Outro', current, getBaseUrl: never }), {});
  assert.deepEqual(planAutoLinkSync([{ id: 'i', data: current }], BASE), []);
});

test('documento antigo (sem whatsappUrlSource): só regenera se o link parece gerado do título', async () => {
  const seeded = { title: 'Vídeo Convite', whatsappUrl: `https://wa.me/5531999044206?text=${encodeURIComponent('Olá, gostaria de saber mais sobre os serviços do Heroi da Cidade! Tenho interesse no serviço: Vídeo Convite')}` };
  assert.ok(looksAutoGenerated(seeded.whatsappUrl, seeded.title));
  const r = await planUpdateWhatsApp({ title: 'Vídeo Novo', current: seeded, getBaseUrl });
  assert.equal(r.whatsappUrlSource, 'auto');

  const custom = { title: 'Vídeo Convite', whatsappUrl: 'https://wa.me/5511977776666?text=Atendimento%20VIP' };
  assert.deepEqual(await planUpdateWhatsApp({ title: 'Outro', current: custom, getBaseUrl: never }), {});

  const noUrl = { title: 'Sem link' };
  assert.equal((await planUpdateWhatsApp({ title: 'Com link', current: noUrl, getBaseUrl })).whatsappUrlSource, 'auto');
});

test('mudança do número padrão: atualiza só auto; manuais, antigos e internos ficam', () => {
  const docs = [
    { id: 'a', data: { title: 'A', whatsappUrlSource: 'auto', whatsappUrl: buildServiceWhatsAppUrl(BASE, 'A') } },
    { id: 'b', data: { title: 'B', whatsappUrlSource: 'manual', whatsappUrl: 'https://wa.me/5511988887777' } },
    { id: 'c', data: { title: 'C', whatsappUrl: buildServiceWhatsAppUrl(BASE, 'C') } },
    { id: 'd', data: { title: 'D', whatsappUrlSource: 'auto', internalOnly: true, whatsappUrl: '' } },
  ];
  const NEW = 'https://wa.me/5511900000000';
  const changes = planAutoLinkSync(docs, NEW);
  assert.deepEqual(changes.map((c) => c.id), ['a']);
  assert.ok(changes[0].whatsappUrl.startsWith(`${NEW}?text=`));
  assert.deepEqual(planAutoLinkSync(docs, BASE), [], 'idempotente: nada a mudar com o mesmo número');
  assert.throws(() => planAutoLinkSync(docs, 'https://wa.me/'), { message: WHATSAPP_NOT_CONFIGURED_MESSAGE });
});

test('validador de link', () => {
  assert.ok(isValidWhatsAppUrl('https://wa.me/5531999044206'));
  assert.ok(!isValidWhatsAppUrl('ftp://wa.me/1'));
  assert.ok(!isValidWhatsAppUrl(''));
});
